FROM datafed:base

WORKDIR /opt/datafed/web

RUN yum update -y
RUN yum install -y \
    g++ \
    protobuf \
    nodejs \
    npm

RUN npm install express
RUN npm install express-session
RUN npm install cookie-parser
RUN npm install helmet
RUN npm install protobufjs
RUN npm install zeromq@5.2.0
RUN npm install ect
RUN npm install client-oauth2

EXPOSE 443

RUN mkdir static
RUN mkdir views

COPY ./web/static static
COPY ./web/views views

ENTRYPOINT ["./datafed-ws.js"]
