FROM datafed/kickstart:centos7

ARG DATAFED_WORKDIR="/apps/datafed"

RUN mkdir -p ${DATAFED_WORKDIR}
ADD . ${DATAFED_WORKDIR}
WORKDIR ${DATAFED_WORKDIR}

# Setup the GNU comipler to devtoolset-7 and compile project
RUN echo "source scl_source enable devtoolset-7" >> /etc/bashrc \
    && source /etc/bashrc \
    && mkdir build \
    && cd build \
    && cmake3 -GNinja ../ \
    && ninja-build


