syntax = "proto3";

package SDMS;

import "messages/dependency_data.proto";

option cc_enable_arenas = true;

message RecordData {
    string id = 1;
    string title = 2;
    string alias = 3;
    string desc = 4;
    repeated string tags = 5;
    string metadata = 6;
    bool external = 7;
    string source = 8;
    string repo_id = 9;
    double size = 10;
    string ext = 11;
    bool ext_auto = 12;
    uint32 ct = 13;
    uint32 ut = 14;
    uint32 dt = 15;
    string owner = 16;
    string creator = 17;
    bool locked = 18;
    string parent_id = 19;
    repeated DependencyData deps = 20;
    uint32 notes = 21;
    string md_err_msg = 22;
    string sch_id = 23;
    uint32 sch_ver = 24;
}
