FROM code.ornl.gov:4567/dlsw/datafed/gcs-base:latest as build

ARG BUILD_DIR="/source"

RUN mkdir -p ${BUILD_DIR}

WORKDIR ${BUILD_DIR}

COPY ./scripts/install_authz_dependencies.sh ${BUILD_DIR}/scripts/

RUN echo "#!/bin/bash\n\$@" > /usr/bin/sudo && chmod +x /usr/bin/sudo
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC ${BUILD_DIR}/scripts/install_authz_dependencies.sh
