syntax = "proto3";

package sdms;

import "messages/dependency_spec_data.proto";

option cc_enable_arenas = true;

message RecordCreateRequest {
    string title = 1;
    string desc = 2;
    repeated string tags = 3;
    string alias = 4;
    string metadata = 5;
    string parent_id = 6;
    bool external = 7;
    string source = 8;
    string repo_id = 9;
    string ext = 10;
    bool ext_auto = 11;
    repeated DependencySpecData deps = 12;
    string sch_id = 13;
    bool sch_enforce = 14;
}
