syntax = "proto3";

package sdms;

import "enums/search_mode.proto";
import "enums/sort_option.proto";

option cc_enable_arenas = true;

message SearchRequest {
    SearchMode mode = 1;
    bool published = 2;
    string id = 3;
    string text = 4;
    repeated string tags = 5;
    repeated string cat_tags = 6;
    uint32 from = 7;
    uint32 to = 8;
    string owner = 9;
    string creator = 10;
    repeated string coll = 11;
    string sch_id = 12;
    string meta = 13;
    bool meta_err = 14;
    SortOption sort = 15;
    bool sort_rev = 16;
    uint32 offset = 17;
    uint32 count = 18;
}
