FROM ubuntu:focal as build

ARG DATAFED_DIR="/datafed"
ARG BUILD_DIR="/datafed/source"
ARG DATAFED_DEPENDENCIES_INSTALL_PATH="/opt/datafed/dependencies"

ENV DATAFED_DEPENDENCIES_INSTALL_PATH="${DATAFED_DEPENDENCIES_INSTALL_PATH}"

RUN mkdir -p ${BUILD_DIR}

WORKDIR ${BUILD_DIR}

COPY ./scripts/dependency_install_functions.sh ${BUILD_DIR}/scripts/
COPY ./scripts/dependency_versions.sh ${BUILD_DIR}/scripts/
COPY ./scripts/generate_datafed.sh ${BUILD_DIR}/scripts/
COPY ./scripts/utils.sh ${BUILD_DIR}/scripts/
COPY ./external/DataFedDependencies/scripts/install_python_client_dependencies.sh ${BUILD_DIR}/scripts/

RUN echo "#!/bin/bash\n\$@" > /usr/bin/sudo && chmod +x /usr/bin/sudo
RUN ${BUILD_DIR}/scripts/generate_datafed.sh
RUN DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC ${BUILD_DIR}/scripts/install_python_client_dependencies.sh
