#!/bin/bash
# Cannot run with -u because we check for unbound variables
# and the script will exit prematurely if '-u' is set
set -ef -o pipefail

SCRIPT=$(realpath "$0")
FILE_NAME=$(basename "${SCRIPT}")
SOURCE=$(dirname "$SCRIPT")
PROJECT_ROOT=$(realpath "${SOURCE}/..")
source "${PROJECT_ROOT}/config/datafed.sh"

VERSION="1.0.1"
echo "$FILE_NAME $VERSION"

ERROR_DETECTED=0
if [ -z "$DATAFED_INSTALL_PATH" ]; then
  echo "Error DATAFED_INSTALL_PATH is not defined in config/datafed.sh, this is"
  echo "      a required argument."
  ERROR_DETECTED=1
fi

if [ -z "$DATAFED_LEGO_EMAIL" ]; then
  echo "Error DATAFED_LEGO_EMAIL is not defined in config/datafed.sh, this is"
  echo "      a required argument."
  ERROR_DETECTED=1
fi

if [ -z "$DATAFED_DOMAIN" ]; then
  echo "Error DATAFED_DOMAIN is not defined in config/datafed.sh, this is"
  echo "      a required argument."
  ERROR_DETECTED=1
fi

if [ "$ERROR_DETECTED" == "1" ]; then
  exit 1
fi

cat <<OUTER_EOF >"$PROJECT_ROOT/scripts/admin_refresh_certs.sh"
#!/bin/bash

# NOTE this script is generated by $SCRIPT, to recreate it change
# settings in datafed.sh and rerun $SCRIPT.
#
# You will still need to make sure this script is registered in cron
# sudo crontab -e
# 0 0 * */2 0 ${DATAFED_INSTALL_PATH}/scripts/admin_refresh_certs.sh
# This script will run every second month if configured in cron with the above
# settings.
# This script should be run with 755 permissions
# and root root
DOMAIN="${DATAFED_DOMAIN}"
systemctl stop datafed-ws.service
lego --accept-tos --email="${DATAFED_LEGO_EMAIL}" --domains="${DATAFED_DOMAIN}" --tls run
DIR_NAME=\$(date +%m-%Y)
mkdir -p "\${DIR_NAME}"
# Create a copy so we can always go back and check when the last time was
# that the job ran successfully
cp ".lego/certificates/${DATAFED_DOMAIN}.key" "\${DIR_NAME}"
cp ".lego/certificates/${DATAFED_DOMAIN}.crt" "\${DIR_NAME}"
mv ".lego/certificates/${DATAFED_DOMAIN}.key" ${DATAFED_INSTALL_PATH}/keys/
mv ".lego/certificates/${DATAFED_DOMAIN}.crt" ${DATAFED_INSTALL_PATH}/keys/
chmod 600 "${DATAFED_INSTALL_PATH}/keys/${DATAFED_DOMAIN}.key"
chmod 600 "${DATAFED_INSTALL_PATH}/keys/${DATAFED_DOMAIN}.crt"
chown root "${DATAFED_INSTALL_PATH}/keys/${DATAFED_DOMAIN}.crt"
chgrp root "${DATAFED_INSTALL_PATH}/keys/${DATAFED_DOMAIN}.crt"
chown root "${DATAFED_INSTALL_PATH}/keys/${DATAFED_DOMAIN}.key"
chgrp root "${DATAFED_INSTALL_PATH}/keys/${DATAFED_DOMAIN}.key"
systemctl start datafed-ws.service

sendmail "$DATAFED_ADMIN_EMAIL" << EOF
To: $DATAFED_ADMIN_EMAIL
From: $DATAFED_SYSTEM_EMAIL
Subject: DataFed Certificate Update

DataFed has updated the web certificates.
EOF
OUTER_EOF

chmod 755 "$PROJECT_ROOT/scripts/admin_refresh_certs.sh"
