
function(find_openssl_library)

  set(OPENSSL_ROOT_DIR "${DEPENDENCY_INSTALL_PATH}")
  set(OPENSSL_USE_STATIC_LIBS TRUE)

  find_package(OpenSSL REQUIRED)

  message("OPENSSL_INCLUDE_DIR = ${OPENSSL_INCLUDE_DIR}\nOPENSSL_LIBRARIES = ${OPENSSL_LIBRARIES}")

  set(OPENSSL_FOUND "${OPENSSL_FOUND}" PARENT_SCOPE)
  set(OPENSSL_INCLUDE_DIR "${OPENSSL_INCLUDE_DIR}" PARENT_SCOPE)
  set(OPENSSL_CRYPTO_LIBRARY "${OPENSSL_CRYPTO_LIBRARY}" PARENT_SCOPE)
  set(OPENSSL_CRYPTO_LIBRARIES "${OPENSSL_CRYPTO_LIBRARIES}" PARENT_SCOPE)
  set(OPENSSL_SSL_LIBRARY "${OPENSSL_SSL_LIBRARY}" PARENT_SCOPE)
  set(OPENSSL_SSL_LIBRARIES "${OPENSSL_SSL_LIBRARIES}" PARENT_SCOPE)
  set(OPENSSL_LIBRARIES "${OPENSSL_LIBRARIES}" PARENT_SCOPE)
  set(OPENSSL_VERSION "${OPENSSL_VERSION}" PARENT_SCOPE)

endfunction()

find_openssl_library()
