
set(DATAFED_RELEASE_YEAR 2023)
set(DATAFED_RELEASE_MONTH 8)
set(DATAFED_RELEASE_DAY 21)
set(DATAFED_RELEASE_HOUR 10)
set(DATAFED_RELEASE_MINUTE 40)

set(DATAFED_COMMON_LIB_MAJOR 0)
set(DATAFED_COMMON_LIB_MINOR 0)
set(DATAFED_COMMON_LIB_PATCH 0)

set(DATAFED_COMMON_PROTOCOL_API_MAJOR 0)
set(DATAFED_COMMON_PROTOCOL_API_MINOR 0)
set(DATAFED_COMMON_PROTOCOL_API_PATCH 0)

set(DATAFED_CORE_MAJOR 0)
set(DATAFED_CORE_MINOR 0)
set(DATAFED_CORE_PATCH 0)

set(DATAFED_FOXX_MAJOR 0)
set(DATAFED_FOXX_MINOR 0)
set(DATAFED_FOXX_PATCH 0)

set(DATAFED_FOXX_API_MAJOR 0)
set(DATAFED_FOXX_API_MINOR 0)
set(DATAFED_FOXX_API_PATCH 0)

set(DATAFED_WEB_MAJOR 0)
set(DATAFED_WEB_MINOR 0)
set(DATAFED_WEB_PATCH 2)

set(DATAFED_REPO_MAJOR 0)
set(DATAFED_REPO_MINOR 0)
set(DATAFED_REPO_PATCH 0)

set(DATAFED_AUTHZ_MAJOR 0)
set(DATAFED_AUTHZ_MINOR 0)
set(DATAFED_AUTHZ_PATCH 0)

set(DATAFED_PYTHON_CLIENT_MAJOR 2)
set(DATAFED_PYTHON_CLIENT_MINOR 0)
set(DATAFED_PYTHON_CLIENT_PATCH 3)
