
function(find_zlib_library)
  # Find zlib
  set(DATAFED_ZLIB_INCLUDE_DIR "${DEPENDENCY_INSTALL_PATH}/include" PARENT_SCOPE)
  set(DATAFED_ZLIB_LIBRARIES "${DEPENDENCY_INSTALL_PATH}/lib/libz.a" PARENT_SCOPE)

  execute_process(
    COMMAND ${CMAKE_CXX_COMPILER} -o ${CMAKE_CURRENT_LIST_DIR}/zlib_version
    ${CMAKE_CURRENT_LIST_DIR}/zlib_version.cpp
    ${DATAFED_ZLIB_LIBRARIES}
    COMMAND ${CMAKE_CURRENT_LIST_DIR}/zlib_version
    OUTPUT_VARIABLE ZLIB_VERSION_OUTPUT
    ERROR_VARIABLE ZLIB_VERSION_ERROR
    RESULT_VARIABLE ZLIB_VERSION_RESULT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE
  )

  set(DATAFED_ZLIB_VERSION_ACTUAL "${ZLIB_VERSION_OUTPUT}" PARENT_SCOPE)

endfunction()

find_zlib_library()
