# Simple workflow for deploying documentation to GitHub Pages
name: Build and deploy documentation

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["master"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    # Single deploy job since we're just deploying
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: generate config file
              run: |
                  ./scripts/generate_datafed.sh
            - name: Install documentation build dependencies
              run: |
                  sudo ./external/DataFedDependencies/scripts/install_docs_dependencies.sh
            - name: Build documentation
              run: |
                  cmake -S. -B build -DBUILD_AUTHZ=OFF -DBUILD_CORE_SERVER=OFF -DBUILD_COMMON=OFF -DBUILD_DOCS=ON -DBUILD_FOXX=OFF -DBUILD_REPO_SERVER=OFF -DBUILD_PYTHON_CLIENT=ON -DBUILD_TESTS=OFF -DBUILD_WEB_SERVER=OFF -DENABLE_UNIT_TESTS=OFF
            - name: Build cmake pydatafed target
              run: |
                  cmake --build build --target pydatafed
            - name: Install pydatafed and depdencies
              run: |
                  python3 -m pip install ./python/datafed_pkg
            - name: Build cmake doc target
              run: |
                  cmake --build build --target docs
            - name: Setup Pages
              uses: actions/configure-pages@v3
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with:
                  # Upload entire repository
                  path: "./docs"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
