#ifndef ERRORCODES_HPP
#define ERRORCODES_HPP

enum {
  EC_BUSY = 1,
  EC_SYNTAX_ERROR,
  EC_INVALID_PATH,
  EC_INVALID_MESSAGE,
  EC_INVALID_OBJECT,
  EC_INVALID_REFERENCE,
  EC_INVALID_OPERATION,
  EC_MISSING_REQUIRED_PARAM,
  EC_INVALID_PARAM,
  EC_OBJECT_ALREADY_EXISTS,
  EC_SCHEMA_MISMATCH,
  EC_PROTO_MISMATCH,
  EC_PROTO_INIT,
  EC_PROTO_SERIALIZE,
  EC_ZMQ_ERROR,
  EC_IO_FAILURE,
  EC_CAPACITY_EXCEEDED,
  EC_INCONSISTENT_STATE,
  EC_INTERNAL_ERROR,
  EC_ACCESS_DENIED
};

#endif  // ERRORCODES_HPP
